version: '3'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "promos"
      TZ: "America/Sao_Paulo"
    ports:
      - "15432:5432"
    networks:
      - pg-db-network
    restart: always

  testaws:
    container_name: testaws
    image: cristhiannrodrigues/testaws:0.0.2-SNAPSHOT
    environment:
      SERVER_PORT: 3000
      TZ: "America/Sao_Paulo"
    ports:
      - "80:3000"
    depends_on:
      - postgres-db
    networks:
      - pg-db-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M

networks:
  pg-db-network:
    driver:  bridge