#server
server:
  port: 8080

#Datasource
spring:
  application:
    name: "sendpromotions"
  datasource:
    url: jdbc:postgresql://localhost:15432/promos
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQL81Dialect

devtools:
  restart:
    enabled: true

promobit:
  limit: 4
  percent: 30

promos:
  url: http://localhost:8080/

#amazon:
#    url: https://www.amazon.com.br/ap/signin?openid.pape.max_auth_age=900&openid.return_to=https%3A%2F%2Fwww.amazon.com.br%2Fgp%2Fyourstore%2Fhome%3Fpath%3D%252Fgp%252Fyourstore%252Fhome%26useRedirectOnSuccess%3D1%26signIn%3D1%26action%3Dsign-out%26ref_%3Dnav_AccountFlyout_signout&openid.assoc_handle=brflex&openid.mode=checkid_setup&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0