#server
server:
  port: 8080

#Datasource
spring:
  application:
    name: "testaws"

  datasource:
    url: jdbc:postgresql://postgres-db:5432/promos
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.PostgreSQL81Dialect

devtools:
  restart:
    enabled: true

promobit:
  limit: 4
  percent: 30

promos:
  url: http://localhost:8080/